
[entities]

	[entities.moth]
		#How many moths required to destroy a torch - Disabled if set to 0
		#Range: > 0
		moths_to_destroy_torch = 5

		[entities.moth.spawning]
			#Enables natural spawning - More info on these options: https://minecraft.fandom.com/wiki/Spawn#Java_Edition
			spawn_naturally = true
			#The spawn weight compared to other entities (typically between 6-20)
			#Range: 1 ~ 9999
			spawn_weight = 10
			#Minimum amount of entities in spawned groups
			#Range: 1 ~ 9999
			minimum_group_size = 1
			#Maximum amount of entities in spawned groups - Must be greater or equal to min value
			#Range: 1 ~ 9999
			maximum_group_size = 3
			#Enter biome IDs. Supports modded biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
			spawn_biomes = ["minecraft:flower_forest", "minecraft:mangrove_swamp", "terralith:birch_taiga", "terralith:shield", "terralith:snowy_cherry_grove", "terralith:white_cliffs", "minecraft:grove", "terralith:siberian_taiga", "terralith:temperate_highlands", "terralith:snowy_maple_forest", "terralith:mirage_isles", "terralith:snowy_shield", "minecraft:swamp", "terralith:lavender_forest", "minecraft:birch_forest", "terralith:lush_valley", "terralith:sakura_grove", "terralith:yosemite_lowlands", "minecraft:dark_forest", "terralith:moonlight_grove", "terralith:ice_marsh", "terralith:forested_highlands", "minecraft:forest", "terralith:orchid_swamp", "terralith:lavender_valley", "terralith:cloud_forest", "terralith:moonlight_valley", "minecraft:old_growth_birch_forest", "terralith:sakura_valley", "terralith:alpine_grove", "terralith:wintry_forest", "terralith:siberian_grove", "terralith:wintry_lowlands"]

			[entities.moth.spawning.spawn_costs]
				#Whether to use spawn costs in spawning or not
				use_spawn_costs = false
				#Cost to spawning algorithm per entity spawned
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				cost_per_spawn = 1.0
				#Maximum cost the spawning algorithm can accrue for this entity
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				maximum_cost_per_biome = 10.0
				#Enter biome IDs to use these costs in. Supports modded biomes. An empty list will use spawn_biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
				spawn_cost_biomes = []

	[entities.hidebehind]

		[entities.hidebehind.spawning]
			#Enables natural spawning - More info on these options: https://minecraft.fandom.com/wiki/Spawn#Java_Edition
			spawn_naturally = true
			#The spawn weight compared to other entities (typically between 6-20)
			#Range: 1 ~ 9999
			spawn_weight = 8
			#Minimum amount of entities in spawned groups
			#Range: 1 ~ 9999
			minimum_group_size = 1
			#Maximum amount of entities in spawned groups - Must be greater or equal to min value
			#Range: 1 ~ 9999
			maximum_group_size = 1
			#Enter biome IDs. Supports modded biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
			spawn_biomes = ["minecraft:flower_forest", "terralith:birch_taiga", "terralith:shield", "terralith:snowy_cherry_grove", "terralith:white_cliffs", "minecraft:grove", "terralith:siberian_taiga", "terralith:temperate_highlands", "terralith:snowy_maple_forest", "terralith:mirage_isles", "terralith:snowy_shield", "terralith:lavender_forest", "minecraft:birch_forest", "terralith:lush_valley", "terralith:sakura_grove", "terralith:yosemite_lowlands", "minecraft:dark_forest", "terralith:moonlight_grove", "terralith:forested_highlands", "minecraft:forest", "terralith:lavender_valley", "terralith:cloud_forest", "terralith:moonlight_valley", "minecraft:old_growth_birch_forest", "terralith:sakura_valley", "terralith:alpine_grove", "terralith:wintry_forest", "terralith:siberian_grove", "terralith:wintry_lowlands"]
			#Enables biome based variant selection. This will make this entity choose variants tailored to the biome they spawn in (Only applies to natural spawns)
			biome_based_variants = true

			[entities.hidebehind.spawning.spawn_costs]
				#Whether to use spawn costs in spawning or not
				use_spawn_costs = false
				#Cost to spawning algorithm per entity spawned
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				cost_per_spawn = 1.0
				#Maximum cost the spawning algorithm can accrue for this entity
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				maximum_cost_per_biome = 10.0
				#Enter biome IDs to use these costs in. Supports modded biomes. An empty list will use spawn_biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
				spawn_cost_biomes = []

	[entities.wisp]
		#Allows the entity to despawn freely when no players are nearby, like vanilla monsters do
		can_despawn = false
		#Chance of wisp being hostile (soul stealer). Chance is a percentage out of 100. 0 is never, 100 is always
		#Range: 0.0 ~ 100.0
		hostile_chance = 12.5

		[entities.wisp.spawning]
			#Enables natural spawning - More info on these options: https://minecraft.fandom.com/wiki/Spawn#Java_Edition
			spawn_naturally = true
			#The spawn weight compared to other entities (typically between 6-20)
			#Range: 1 ~ 9999
			spawn_weight = 13
			#Minimum amount of entities in spawned groups
			#Range: 1 ~ 9999
			minimum_group_size = 1
			#Maximum amount of entities in spawned groups - Must be greater or equal to min value
			#Range: 1 ~ 9999
			maximum_group_size = 3
			#Enter biome IDs. Supports modded biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
			spawn_biomes = ["minecraft:flower_forest", "minecraft:mangrove_swamp", "terralith:birch_taiga", "terralith:shield", "terralith:snowy_cherry_grove", "terralith:white_cliffs", "minecraft:grove", "terralith:siberian_taiga", "terralith:temperate_highlands", "terralith:snowy_maple_forest", "terralith:mirage_isles", "terralith:snowy_shield", "minecraft:swamp", "terralith:lavender_forest", "minecraft:birch_forest", "terralith:lush_valley", "terralith:sakura_grove", "terralith:yosemite_lowlands", "minecraft:dark_forest", "terralith:moonlight_grove", "terralith:ice_marsh", "terralith:forested_highlands", "minecraft:forest", "terralith:orchid_swamp", "terralith:lavender_valley", "terralith:cloud_forest", "terralith:moonlight_valley", "minecraft:old_growth_birch_forest", "terralith:sakura_valley", "terralith:alpine_grove", "terralith:wintry_forest", "terralith:siberian_grove", "terralith:wintry_lowlands"]

			[entities.wisp.spawning.spawn_costs]
				#Whether to use spawn costs in spawning or not
				use_spawn_costs = false
				#Cost to spawning algorithm per entity spawned
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				cost_per_spawn = 1.0
				#Maximum cost the spawning algorithm can accrue for this entity
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				maximum_cost_per_biome = 10.0
				#Enter biome IDs to use these costs in. Supports modded biomes. An empty list will use spawn_biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
				spawn_cost_biomes = []

	[entities.hirschgeist]
		#Allows the entity to despawn freely when no players are nearby, like vanilla monsters do
		can_despawn = false

		[entities.hirschgeist.spawning]
			#Enables natural spawning - More info on these options: https://minecraft.fandom.com/wiki/Spawn#Java_Edition
			spawn_naturally = true
			#The spawn weight compared to other entities (typically between 6-20)
			#Range: 1 ~ 9999
			spawn_weight = 2
			#Minimum amount of entities in spawned groups
			#Range: 1 ~ 9999
			minimum_group_size = 1
			#Maximum amount of entities in spawned groups - Must be greater or equal to min value
			#Range: 1 ~ 9999
			maximum_group_size = 1
			#Enter biome IDs. Supports modded biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
			spawn_biomes = ["minecraft:flower_forest", "terralith:birch_taiga", "terralith:shield", "terralith:snowy_cherry_grove", "terralith:white_cliffs", "minecraft:grove", "terralith:siberian_taiga", "terralith:temperate_highlands", "terralith:snowy_maple_forest", "terralith:mirage_isles", "terralith:snowy_shield", "terralith:lavender_forest", "minecraft:birch_forest", "terralith:lush_valley", "terralith:sakura_grove", "terralith:yosemite_lowlands", "minecraft:dark_forest", "terralith:moonlight_grove", "terralith:forested_highlands", "minecraft:forest", "terralith:lavender_valley", "terralith:cloud_forest", "terralith:moonlight_valley", "minecraft:old_growth_birch_forest", "terralith:sakura_valley", "terralith:alpine_grove", "terralith:wintry_forest", "terralith:siberian_grove", "terralith:wintry_lowlands"]

			[entities.hirschgeist.spawning.spawn_costs]
				#Whether to use spawn costs in spawning or not
				use_spawn_costs = false
				#Cost to spawning algorithm per entity spawned
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				cost_per_spawn = 1.0
				#Maximum cost the spawning algorithm can accrue for this entity
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				maximum_cost_per_biome = 10.0
				#Enter biome IDs to use these costs in. Supports modded biomes. An empty list will use spawn_biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
				spawn_cost_biomes = []

	[entities.zotzpyre]

		[entities.zotzpyre.spawning]
			#Enables natural spawning - More info on these options: https://minecraft.fandom.com/wiki/Spawn#Java_Edition
			spawn_naturally = true
			#The spawn weight compared to other entities (typically between 6-20)
			#Range: 1 ~ 9999
			spawn_weight = 30
			#Minimum amount of entities in spawned groups
			#Range: 1 ~ 9999
			minimum_group_size = 1
			#Maximum amount of entities in spawned groups - Must be greater or equal to min value
			#Range: 1 ~ 9999
			maximum_group_size = 1
			#Enter biome IDs. Supports modded biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
			spawn_biomes = ["terralith:ashen_savanna", "terralith:birch_taiga", "terralith:haze_mountain", "terralith:gravel_desert", "minecraft:sparse_jungle", "terralith:gravel_beach", "terralith:rocky_shrubland", "terralith:basalt_cliffs", "minecraft:windswept_hills", "terralith:temperate_highlands", "minecraft:stony_peaks", "terralith:emerald_peaks", "terralith:alpine_highlands", "terralith:mirage_isles", "terralith:amethyst_canyon", "terralith:snowy_shield", "terralith:amethyst_rainforest", "minecraft:bamboo_jungle", "minecraft:swamp", "minecraft:birch_forest", "minecraft:snowy_taiga", "terralith:yosemite_lowlands", "minecraft:dark_forest", "terralith:moonlight_grove", "minecraft:frozen_peaks", "terralith:scarlet_mountains", "minecraft:lush_caves", "terralith:yellowstone", "minecraft:meadow", "minecraft:old_growth_pine_taiga", "terralith:orchid_swamp", "minecraft:jagged_peaks", "minecraft:old_growth_birch_forest", "terralith:caldera", "terralith:wintry_forest", "terralith:wintry_lowlands", "minecraft:taiga", "minecraft:flower_forest", "terralith:tropical_jungle", "minecraft:mangrove_swamp", "terralith:shield", "minecraft:cherry_grove", "terralith:snowy_cherry_grove", "terralith:white_cliffs", "minecraft:snowy_beach", "minecraft:grove", "terralith:siberian_taiga", "minecraft:windswept_gravelly_hills", "terralith:snowy_maple_forest", "minecraft:jungle", "terralith:snowy_badlands", "minecraft:snowy_slopes", "terralith:rocky_jungle", "terralith:cave/underground_jungle", "terralith:lavender_forest", "terralith:lush_valley", "terralith:sakura_grove", "minecraft:windswept_forest", "terralith:ice_marsh", "terralith:fractured_savanna", "terralith:volcanic_crater", "terralith:forested_highlands", "minecraft:beach", "terralith:rocky_mountains", "terralith:bryce_canyon", "minecraft:forest", "minecraft:snowy_plains", "terralith:volcanic_peaks", "terralith:lavender_valley", "terralith:cloud_forest", "terralith:moonlight_valley", "terralith:sakura_valley", "terralith:alpine_grove", "terralith:jungle_mountains", "terralith:siberian_grove"]

			[entities.zotzpyre.spawning.spawn_costs]
				#Whether to use spawn costs in spawning or not
				use_spawn_costs = false
				#Cost to spawning algorithm per entity spawned
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				cost_per_spawn = 1.0
				#Maximum cost the spawning algorithm can accrue for this entity
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				maximum_cost_per_biome = 10.0
				#Enter biome IDs to use these costs in. Supports modded biomes. An empty list will use spawn_biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
				spawn_cost_biomes = []

